type: local
data_dir: /home/alex/Kaggle/DSS/data/child-mind-institute-detect-sleep-states
processed_dir: /home/alex/Kaggle/DSS/processed_data
output_dir: /home/alex/Kaggle/DSS/output
model_dir: /home/alex/Kaggle/DSS/output/train
t_automodel_dir: /home/alex/Kaggle/DSS/deberta-v3-small
sub_dir: ./
