# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN
  - feature_extractor: CNNSpectrogram
  - decoder: TransformerDecoder
  - split: fold_3

seed: 42
exp_name: dummy
duration: 8640 # duration is a multiple of 32, duration * 5 = number of seconds
downsample_rate: 2
upsample_rate: 1

# training
epoch: 50
batch_size: 24
num_workers: 12
accelerator: auto
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 2 # 1
monitor: val_loss
monitor_mode: min
check_val_every_n_epoch: 1

# Dataset
offset: 20 # length of gaussian kernel
sigma: 6
bg_sampling_rate: 0.5 # probability of negative samples

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4
  
# post_process
post_process:
  score_th: 0.0001
  distance: 90

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"

# feature
features:
  - "anglez"
  - "enmo"
  # - "month_sin"
  # - "month_cos"
  - "hour_sin"
  - "hour_cos"
  # - "minute_sin"
  # - "minute_cos"
  # - "sun_event"
  # - "week_sin"
  # - "week_cos"

# optimizer
optimizer:
  lr: 5e-4

# scheduler
scheduler:
  type: base # min_lr
  min_lr: 1e-4
  min_epoch: 30
  num_warmup_steps: 0
